export const projects = [
  {
    id: 1,
    name: 'team7-showcase',
    description: 'The very website you are looking at. A digital hub for our club.',
    language: 'TypeScript',
    languageColor: 'bg-blue-500',
    stars: 128,
    forks: 12,
    status: 'Public',
    updatedAt: '2 hours ago',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'website user interface'
  },
  {
    id: 2,
    name: 'algo-visualizer',
    description: 'An interactive platform to visualize common data structures and algorithms.',
    language: 'Python',
    languageColor: 'bg-yellow-500',
    stars: 256,
    forks: 45,
    status: 'Public',
    updatedAt: 'on 24 May',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'algorithm visualization'
  },
  {
    id: 3,
    name: 'campus-event-api',
    description: 'A robust REST API for managing campus events, built with Go.',
    language: 'Go',
    languageColor: 'bg-cyan-500',
    stars: 92,
    forks: 5,
    status: 'Public',
    updatedAt: 'on 20 May',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'code api'
  },
  {
    id: 4,
    name: 'mobile-study-app',
    description: 'A React Native application to help students organize their study schedules.',
    language: 'TypeScript',
    languageColor: 'bg-blue-500',
    stars: 150,
    forks: 22,
    status: 'In Progress',
    updatedAt: 'on 18 May',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'mobile app'
  },
];

export const members = [
  {
    id: 1,
    name: 'Ada Lovelace',
    username: 'ada',
    avatarUrl: 'https://placehold.co/80x80.png',
    dataAiHint: 'woman portrait',
    bio: 'Pioneering the future of computing.',
    role: 'President',
    socials: { github: 'ada', linkedin: 'ada-lovelace' },
  },
  {
    id: 2,
    name: 'Grace Hopper',
    username: 'grace',
    avatarUrl: 'https://placehold.co/80x80.png',
    dataAiHint: 'woman portrait',
    bio: 'Lead Mentor. Inventor of the first compiler.',
    role: 'Lead Mentor',
    socials: { github: 'grace', linkedin: 'grace-hopper' },
  },
  {
    id: 3,
    name: 'Alan Turing',
    username: 'alan',
    avatarUrl: 'https://placehold.co/80x80.png',
    dataAiHint: 'man portrait',
    bio: 'Breaking codes and building machines.',
    role: 'Core Member',
    socials: { github: 'alan', linkedin: 'alan-turing' },
  },
  {
    id: 4,
    name: 'Linus Torvalds',
    username: 'linus',
    avatarUrl: 'https://placehold.co/80x80.png',
    dataAiHint: 'man portrait',
    bio: 'Just for fun.',
    role: 'Core Member',
    socials: { github: 'linus', linkedin: 'linus-torvalds' },
  },
];

export const events = [
  {
    id: 1,
    title: 'Workshop: Intro to Next.js 14',
    type: 'Workshop',
    status: 'Open',
    date: '2024-08-15',
    location: 'Room 404, CS Building',
    author: 'grace',
  },
  {
    id: 2,
    title: 'Tech Talk: The Future of AI in Development',
    type: 'Talk',
    status: 'Open',
    date: '2024-09-01',
    location: 'Virtual (Zoom)',
    author: 'ada',
  },
  {
    id: 3,
    title: 'Fall Hackathon 2024',
    type: 'Hackathon',
    status: 'Closed',
    date: '2024-09-20',
    location: 'Main Auditorium',
    author: 'alan',
  },
];